spring.application.name=ejercicio10

spring.datasource.url=jdbc:postgresql://dpg-d7oa7sv7f7vs7389pnt0-a.oregon-postgres.render.com:5432/bd_prog4_lozano?sslmode=require
spring.datasource.username=bd_prog4_lozano_user
spring.datasource.password=JX3JE4cSFB82708DxqyB8LQsgpHBpkzX

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true